### PR TITLE
Fix listAvailableLanguageInformation

### PR DESCRIPTION
**Pull request by reinhardt**
Refs https://github.com/plone/plone.i18n/issues/40

### CODE REVIEW

**Comment by reinhardt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by reinhardt** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
There are errors in `plone.app.i18n` and `plone.app.multilingual`.

**Comment by reinhardt** [comment]
> There are errors in `plone.app.i18n` and `plone.app.multilingual`.

FWIW, on my local machine I can reproduce the failures in `plone.app.i18n` regardless of what branch of `plone.i18n` is checked out, and I cannot reproduce the failures in `plone.app.multilingual` at all (using python 3.7).

**Comment by mauritsvanrees** [comment]
I see the problem. You are missing some changes from master. The flags were changed in PR #42. If you merge or rebase on master, the test failures should be gone.

But I see that this method is not actually called anywhere. This was already true in Plone 4.3, when this method was in `Products/PloneLanguageTool/LanguageTool.py`. It seems like a logical method to call though. That makes me wonder how other parts of Plone get a list of available languages. Maybe those places *could* call this method instead of what they are doing now.

The same is true for `listAvailableCountries` in the same file. Also not used. And it has the same problem with `sort` not working on Python 3.

I would suggest to remove these methods, except that Plone 6 is in beta, so we should not do that.

Maybe fix both methods and add some tests so the code gets called and we know if something breaks?

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
> I would suggest to remove these methods, except that Plone 6 is in beta, so we should not do that.

I would `@deprecate` those.

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
I was about to cut a final release but better get this in before it 🍀

**Pull request merged**
