### PR TITLE
Break circular reference by moving interface to this package.

### LINKED ISSUE #29: Break circular dependency between `plone.i18n` and `Products.CMFPlone`.
As proposed in https://github.com/plone/Products.CMFPlone/issues/2049 we would like to get rid of the circular dependency between `plone.i18n` and `Products.CMFPlone`. In principal, the `ILanguageSchema` interface is the only import used from `Products.CMFPlone`, so the idea was to move the interface definition to this package and add a BBB import in `Products.CMFPlone`.

### PR DESCRIPTION
**Pull request by sallner**
Fixes #29 .

Explicitly declare dependencies which have been there implicitly by depending on Products.CMFPlone.

The interface should be imported in `Products.CMFPlone.interfaces` after the merge.

### CODE REVIEW

**Comment by sallner** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Is there a PR for Products.CMFPlone already?

**Comment by sallner** [comment]
> Is there a PR for Products.CMFPlone already?

@jensens No, I actually do not know the procedure to do this, as I would need both branches, here and in [plone/Products.CMFPlone](https://github.com/plone/Products.CMFPlone.) So where would be the correct place to do this? My plone contributor skills are not fully developed yet.  

Should I leave this PR open till the one on CMFPlone was successful?

**Comment by jensens** [comment]
Open two PR's and then log in to Jenkins and fill in both PRs into the fields at https://jenkins.plone.org/job/pull-request-5.2/build?delay=0sec (and for 5.2-3.6 and 5.2-3.7 jobs as above linked in the checks)

**Comment by gforcada** [comment]
Actually, as this pull request alone can be merged, tests do not break seems, we can merge this one and shortly after create the other in CMFPlone :+1: 

Or better, prepare the other pull request, and once it has been reviewed (ignore the test failures), let's merge this one and then test the other.

**Pull request merged**
