### PR TITLE
Moved negotiator code from PTS over here

### PR DESCRIPTION
**Pull request by jensens**
merge with 
- https://github.com/plone/plone.app.testing/pull/46
- https://github.com/plone/buildout.coredev/pull/399

### CODE REVIEW

**Comment by jensens** [comment]
Looks like tests are not starting in the combination of buildout branch + any package branch (stops early at git checkout time). @plone/testing-team @gforcada any ideas why?

**Comment by mauritsvanrees** [comment]
A few [errors in Archetypes](http://jenkins.plone.org/job/plone-5.2-python-2.7-at/359/testReport/junit/Products.Archetypes.tests.test_pawidgets/ArchetypesVocabularyPermissionTests/test_vocabulary_field_wrong_vocab_disallowed/) due to this change. During the move you renamed `l` to `ll`, which is very good, but you missed one. I fixed it in da6efb5ace88493e7592966d6ae9895cce098a3b directly on master.

**Comment by mauritsvanrees** [comment]
Phew, all is green again.

**Comment by jensens** [comment]
Thanks for all your help!

**Pull request merged**
